url: https://sonjak3.github.io
baseurl: /vrgrads

# Site settings
title: ARails
email: sonjak3@cs
description: "Augmented Reality game."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: acd1d2
  secondary: 85a5ad
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jenny Kang
  pic: 1.jpg
  position: Software Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jsykang

- name: Sonja Khan
  pic: 2.png
  position: Software Developer
  social:
    - title: github
      url: https://github.com/sonjakhan
    - title: instagram
      url: https://www.instagram.com/sonjak3/
    - title: twitter
      url: https://twitter.com/sonjathewrecker

- name: Riley Porter
  pic: 3.png
  position: Software Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/riley-porter-b6444b62
    - title: github
      url: https://github.com/rileyporter
    - title: instagram
      url: https://www.instagram.com/ryporter/

- name: Nick Reiter
  pic: 4.png
  position: Software Developer
  social:
    - title: twitter
      url: https://twitter.com/scriptreiter
    - title: facebook
      url: https://www.facebook.com/scriptreiter
    - title: linkedin
      url: https://www.linkedin.com/in/scriptreiter


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty