url: https://sonjak3.github.io
baseurl: /vrgrads

# Site settings
title: AR Railway
email: sonjak3@cs
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: acd1d2
  secondary: 85a5ad
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Jenny Kang
  pic: 1
  position: Software Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sonja Khan
  pic: 2
  position: Software Developer
  social:
    - title: twitter
      url: https://twitter.com/sonjathewrecker
    - title: instagram
      url: https://www.instagram.com/sonjak3/
    - title: linkedin
      url: http://linkedin.com/in/sonjakhan

- name: Riley Porter
  pic: 3
  position: Software Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Nick Reiter
  pic: 4
  position: Software Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty